#!/bin/bash

# DATA=import.xml
if [ $# -lt 1 ]; then
    echo "Usage: csimport XML-filename"
    exit
fi

# URL="http://cinefiles.cspace.berkeley.edu/cspace-services/imports?type=xml"
#URL="http://li669-192.members.linode.com:8180/cspace-services/imports?type=xml"
URL="http://ucjeps-dev.cspace.berkeley.edu:8180/cspace-services/imports?type=xml"
CONTENT_TYPE="Content-Type: application/xml"
FILE_TYPE=";type=application/xml"
USER="CSPACEUSERNAME:REDACTEDPASSWORD"

m=`date +"%m"`
d=`date +"%d"`
y=`date +"%Y"`
LOGFILE=curl_log.$y$m$d

n=0
while [ $# -gt 0 ]; do
    DATA=$1
    cat /dev/null > curl.out.${DATA}
    echo "Sending $DATA"
    echo "to $URL"
    echo "with content type $CONTENT_TYPE"
    echo "as $USER"

    curl -X POST -i -u "$USER" -H "$CONTENT_TYPE" $URL -T $DATA -o curl.out.${DATA}
#  curl -X POST -i -u "$USER" -H "$CONTENT_TYPE" $URL -T $DATA
#    curl -i -u "$USER" ${URL}?impTimout=900 -F "file=@${DATA}${FILE_TYPE}" -o curl.out.${DATA}

    # Cout number of import records read by "curl" and append to a log file.
    echo "Counting $DATA ---" >> $LOGFILE
    grep READ curl.out.${DATA} | wc -l >> $LOGFILE

    shift
    n=`expr $n + 1`

#   mv $DATA ${DATA}.done

done
echo "$n file(s) processed"
